import { isoDate } from "@/lib/exports/format";
import { getCoverLayers } from "@/lib/coverage";

export type IcsProduct = {
  id: string;
  name: string;
  brand: string | null;
  serialNumber: string | null;
  invoiceNumber: string | null;
  warrantyExpiry: Date | string | null;
  extendedExpiry?: Date | string | null;
  extendedType?: string | null;
};

function escapeIcsText(value: string) {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/\n/g, "\\n")
    .replace(/,/g, "\\,")
    .replace(/;/g, "\\;");
}

function foldLine(line: string) {
  if (line.length <= 75) return line;

  const parts: string[] = [];
  let remaining = line;

  while (remaining.length > 75) {
    parts.push(remaining.slice(0, 75));
    remaining = ` ${remaining.slice(75)}`;
  }

  parts.push(remaining);
  return parts.join("\r\n");
}

function stampUtc(date = new Date()) {
  return date.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z");
}

function nextDayCompact(iso: string) {
  const date = new Date(`${iso}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() + 1);
  return date.toISOString().slice(0, 10).replace(/-/g, "");
}

export function productsToIcs(
  products: IcsProduct[],
  options?: { calendarName?: string; now?: Date }
) {
  const calendarName = options?.calendarName ?? "Warranty Vault";
  const now = options?.now ?? new Date();

  const events = products.flatMap((product) => {
    const description = [
      product.brand ? `Brand: ${product.brand}` : null,
      product.serialNumber ? `Serial: ${product.serialNumber}` : null,
      product.invoiceNumber ? `Invoice: ${product.invoiceNumber}` : null,
      "Generated by Warranty Vault",
    ]
      .filter((line): line is string => Boolean(line))
      .map(escapeIcsText)
      .join("\\n");

    return getCoverLayers(product).flatMap((layer) => {
      const expiry = isoDate(layer.date);
      if (!expiry) return [];

      const compact = expiry.replace(/-/g, "");
      const uid =
        layer.id === "extended"
          ? `${product.id}-extended@warrantyvault.in`
          : `${product.id}@warrantyvault.in`;
      const summary =
        layer.id === "extended"
          ? `${layer.label} expires: ${product.name}`
          : `Warranty expires: ${product.name}`;

      return [
        "BEGIN:VEVENT",
        foldLine(`UID:${uid}`),
        `DTSTAMP:${stampUtc(now)}`,
        `DTSTART;VALUE=DATE:${compact}`,
        `DTEND;VALUE=DATE:${nextDayCompact(expiry)}`,
        foldLine(`SUMMARY:${escapeIcsText(summary)}`),
        foldLine(`DESCRIPTION:${description}`),
        "END:VEVENT",
      ];
    });
  });

  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Warranty Vault//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    foldLine(`X-WR-CALNAME:${escapeIcsText(calendarName)}`),
    ...events,
    "END:VCALENDAR",
  ].join("\r\n") + "\r\n";
}
